[project]
name = "sql-datawarehouse"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-cloud-bigquery>=3.38.0",
    "google-cloud-storage>=3.6.0",
    "python-dotenv>=1.2.1",
]
